### ISSUE TITLE
theme-iemo主题发布文章里使用行内代码功能无效，发布后字体无法显示为行内代码字体。

### ISSUE THREAD

**Issue by aling466** [chengzhongxue/halo-theme-iemo#10]
theme-iemo主题发布文章里使用行内代码功能无效，发布后字体无法显示为行内代码字体。

![image](https://github.com/user-attachments/assets/0e3c7188-0cab-460b-a52d-5a87a240e6f6)

显示成普通字体了
![image](https://github.com/user-attachments/assets/4b6cb2e5-b3a0-44fd-b08a-ca0e280f6f1e)
[Uploading halo-log-2024-09-02 12_32.log…]()

运行环境：

- 外部访问地址: 
- 启动时间: 2024-09-02 10:51
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.1.74-Unraid
- 已激活主题: [iEmo 1.0.2](https://github.com/chengzhongxue/halo-theme-iemo)
- 已启动插件:
  - [live2d 看板娘 1.2.1](https://github.com/LIlGG/plugin-live2d)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

**Comment by chengzhongxue** [comment]
#
