### ISSUE TITLE
主题/archives标签页的标题是分类

### ISSUE THREAD

**Issue by wangdamao0908** [chengzhongxue/halo-theme-iemo#4]
地址：https://blog.wlazycat.net/archives
此处的标题应该是归档才正确

**Comment by XieArui** [comment]
同样，我在这个地方也有类似的问题，我在halo后台菜单里添加了探针的自定义链接后在前台分类下面也出现了这个，后来菜单里删了自定义链接，这个分类还在
![image](https://image.tuhao.eu.org/file/72433ef65d36475f5d9e0.png)
这个该怎么解决啊？
这个主题的分类这方便的设置有点摸不着头脑

**Comment by XieArui** [comment]
> 地址：https://blog.wlazycat.net/archives 此处的标题应该是归档才正确

你是怎么做到分类这么明白的？可以看看你的halo后台菜单的截图吗？

**Comment by wangdamao0908** [comment]
> > 地址：https://blog.wlazycat.net/archives 此处的标题应该是归档才正确
> 
> 你是怎么做到分类这么明白的？可以看看你的halo后台菜单的截图吗？
![.PNG](https://s2.loli.net/2024/06/18/CjrVn9TkhFX4QYG.png)
我分的也不是很复杂

**Comment by AlexeiLeery** [comment]
我在iEmo主题里遇到了一些问题，我在halo后台菜单里新建了菜单后结果iEmo前台显示出来的还有我删掉的旧的菜单选项，如图：
![](https://image.tuhao.eu.org/file/c357b6d3304352a75c1db.png)
![](https://image.tuhao.eu.org/file/f273bed5a14c285ac0d9d.png)
请问这个该怎么解决啊？快愁死我了

**Comment by wangdamao0908** [comment]
> > > > 地址：https://blog.wlazycat.net/archives 此处的标题应该是归档才正确
> > > 
> > > 
> > > 你是怎么做到分类这么明白的？可以看看你的halo后台菜单的截图吗？
> > > ![.PNG](https://camo.githubusercontent.com/d4276626af64b3ecc53982a66075e3cb16e6d60e501e86595ac4468c9fff19c9/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30362f31382f436a72566e39546b684658345159472e706e67)
> > > 我分的也不是很复杂
> 
> 我在iEmo主题里遇到了一些问题，我在halo后台菜单里新建了菜单后结果iEmo前台显示出来的还有我删掉的旧的菜单选项，如图： ![](https://camo.githubusercontent.com/8ff217f283e8f5b63eb6356f5ed3574626e337adbfaa77e7d6639df75c46f36c/68747470733a2f2f696d6167652e747568616f2e65752e6f72672f66696c652f6333353762366433333034333532613735633164622e706e67) ![](https://camo.githubusercontent.com/ba2ee5058c8ca0084fc280a8b8a2651b4d4f444d54d7143565c2ca79e6893eac/68747470733a2f2f696d6167652e747568616f2e65752e6f72672f66696c652f6632373362656435613134633238356163306439642e706e67) 请问这个该怎么解决啊？快愁死我了

没有遇到这种情况，你可以尝试换个浏览器或者清理一下缓存

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/halo-theme-iemo/assets/89380218/8209f8fe-ca27-49ce-9ded-bd2dcabc4531)
这个弄错了

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/halo-theme-iemo/assets/89380218/8209f8fe-ca27-49ce-9ded-bd2dcabc4531)
这个弄错了

> 地址：https://blog.wlazycat.net/archives 此处的标题应该是归档才正确

弄错了。下个版本更新

**Comment by AlexeiLeery** [comment]
> > > > > 地址：https://blog.wlazycat.net/archives 此处的标题应该是归档才正确
> > > > 
> > > > 
> > > > 你是怎么做到分类这么明白的？可以看看你的halo后台菜单的截图吗？
> > > > ![.PNG](https://camo.githubusercontent.com/d4276626af64b3ecc53982a66075e3cb16e6d60e501e86595ac4468c9fff19c9/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30362f31382f436a72566e39546b684658345159472e706e67)
> > > > 我分的也不是很复杂
> > 
> > 
> > 我在iEmo主题里遇到了一些问题，我在halo后台菜单里新建了菜单后结果iEmo前台显示出来的还有我删掉的旧的菜单选项，如图： ![](https://camo.githubusercontent.com/8ff217f283e8f5b63eb6356f5ed3574626e337adbfaa77e7d6639df75c46f36c/68747470733a2f2f696d6167652e747568616f2e65752e6f72672f66696c652f6333353762366433333034333532613735633164622e706e67) ![](https://camo.githubusercontent.com/ba2ee5058c8ca0084fc280a8b8a2651b4d4f444d54d7143565c2ca79e6893eac/68747470733a2f2f696d6167652e747568616f2e65752e6f72672f66696c652f6632373362656435613134633238356163306439642e706e67) 请问这个该怎么解决啊？快愁死我了
> 
> 没有遇到这种情况，你可以尝试换个浏览器或者清理一下缓存

已解决，是文章哪里设置的文章分类有关，删掉就正常了

**Comment by chengzhongxue** [comment]
1.0.2版本已解决
